### ISSUE TITLE
[Feature] Add Languages

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#156]
- [x] **Chinese**
e.g. https://www.yundongfang.com/Yun45447.html, https://www.rjno1.com/systemtraymenu/

- [x] **Czech**
e.g. https://www.chip.cz/novinky/windows-10-diky-bezplatnemu-nastroji-ziskate-druhou-nabidku-start/

- [x] **Dutch**  ,  #162 Thank you @HansieNL
e.g. https://www.microsoft.com/nl-nl/p/systemtraymenu/9n24f8zbjmt1?cid=msft_web_appsforwindows_chart&activetab=pivot:overviewtab

- [x] **French** #145: Thank you @PascalAloy
 e.g. https://www.justgeek.fr/systemtraymenu-une-alternative-open-source-au-menu-demarrer-70225/
 
- [x] **Japanese**
 e.g. https://softaro.net/systemtraymenu/

- [x] **Italian**
e.g. https://www.tecnobabele.com/crea-un-menu-di-avvio-personalizzato-a-cui-puoi-accedere-con-un-tasto-di-scelta-rapida-utilizzando-systemtraymenu/2021-04-11/
 
- [x] **Korean** 
e.g. https://windowsforum.kr/data/16000741

- [x] **Portuguese** #163 Thank you @igorruckert
e.g. https://www.softdownload.com.br/crie-menu-programas-favoritos-systemtraymenu.html

 - [x] **Russian**
 e.g. https://www.white-windows.ru/systemtraymenu-podobie-menyu-pusk-no-bolee-prostoe-i-rabotayushhee-iz-sistemnogo-treya/

- [x] **Spanish** #150: [Feature] Add Spanish 
e.g. https://vipreplica.es/apps/agregue-atajos-carpetas-url-y-acceda-a-ellos-desde-un-menu-compacto-con-systemtraymenu/

 - [x] **Vietnamese** 
e.g. https://baominh.tech/systemtraymenu-tao-menu-start-tuy-chinh-duoi-khai-he-thong.html
